export const menuItems = [
    {
        id: 1,
        name: "Jollof Rice Special",
        category: "Food",
        price: 10000,
        image: "/slide1.jpg",
        description: "Smoky party jollof with grilled chicken",
        mealTime: ["lunch", "dinner"],
    },
    {
        id: 2,
        name: "Lime Juice",
        category: "Drinks",
        price: 5000,
        image: "/lime-juice.jpg",
        description: "Refreshing Natural mocktail",
        mealTime: ["breakfast", "lunch", "dinner"],

    },
    {
        id: 3,
        name: "Vegetable Soup & Pounded Yam",
        category: "Food",
        price: 50000,
        image: "/slide3.jpg",
        description: "vegetable soup and goat meat served with pounded yam",
        mealTime: ["lunch", "dinner"],
    },
    {
        id: 4, 
        name: "Donut",
        category: "Desserts",
        price: 5000,
        image: "/donut.jpg",
        description: "Soft Donut with sprinkle chocolate and candy",
        mealTime: ["breakfast", "lunch"],
    },
    {
        id: 5,
        name: "White Rice",
        category: "Food",
        price: 50000,
        image: "/slide2.jpg",
        description: "Delicious white rice served with grid pepper", 
        mealTime: ["lunch", "dinner"],
    },
    {
        id: 6,
        name: "Coffee",
        category: "Drinks",
        price: 3000,
        image: "/coffee.jpg",
        description: "Hot Cup of precious Coffee",
         mealTime: ["breakfast"],
    },
    {
        id: 7,
        name: "Puff Puff",
        category: "Desserts",
        price: 2000,
        image: "/puf-puf.jpg",
        description: "Sweet, fluffy Nigerian fried dough balls",
        mealTime: ["breakfast", "lunch"],
    },
    {
        id: 8,
        name: "Chin Chin",
        category: "Desserts",
        price: 3000,
        image: "/chin-chin.jpg",
        description: "Crunchy sweet fried pastry snack",
        mealTime: ["breakfast", "lunch"],
    },
    {
        id: 9,
        name: "Chocolate Cake",
        category: "Desserts",
        price: 3000,
        image: "/chocolate-cake.jpg",
        description: "Satisfy your Cravins with our Freshly made Chocolate Cake",
        mealTime: ["breakfast", "lunch"],
    },
    {
        id: 10,
        name: "Chilled Coke",
        category: "Drinks",
        price: 3000,
        image: "/coke.jpg",
        description: "Refreshing cold and always satisfying",
        mealTime: ["breakfast", "lunch", "dinner"],
    }
];